name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: [23.x, 24.x, 25.x]
        elixir: [1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x]
        exclude:
          - otp: 25.x
            elixir: 1.11.x
          - otp: 25.x
            elixir: 1.12.x
          - otp: 25.x
            elixir: 1.10.x
          - otp: 24.x
            elixir: 1.10.x
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Install Dependencies
        run: |
          mix deps.get --only test

      - name: Run tests
        run: mix test

      - name: Check formatter
        run: mix format --check-formatted
